name: lint, build, and test
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: gradle/actions/setup-gradle@v3

      - name: Lint
        run: ./gradlew lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: gradle/actions/setup-gradle@v3

      - name: Build the app
        run: ./gradlew build -x lint

      - uses: actions/upload-artifact@v4
        with:
          path: app/build/outputs/apk/debug/app-debug.apk
          name: app-debug

      - uses: actions/upload-artifact@v4
        with:
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          name: app-release-unsigned

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Delete unnecessary tools to free up some space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: false # Don't remove Android tools
          large-packages: false # includes google-cloud-sdk and it's slow
          tool-cache: true
          dotnet: true
          haskell: true
          swap-storage: true
          docker-images: true

      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: gradle/actions/setup-gradle@v3

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Accept Android licenses
        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true
